name: 'Jest → Compass'
description: 'Upload Jest metrics to Compass'
inputs:
  jira-user:
    description: 'JIRA User'
    required: true
  jira-token:
    description: 'JIRA API Token'
    required: true
  test-script:
    description: 'Run tests script'
    required: true
    default: 'npm test'
outputs:
  percent:
    description: 'Total coverage percent'
runs:
  using: 'node20'
  main: 'dist/index.js'
